export const useInfiniteScrollScreen = () => {
    const list = [
        { username: "User1", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "completed" },
        { username: "User2", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "failed" },
        { username: "User3", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User4", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User5", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "completed" },
        { username: "User6", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "failed" },
        { username: "User7", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User8", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User9", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "completed" },
        { username: "User10", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "failed" },
        { username: "User11", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User12", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User13", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "completed" },
        { username: "User14", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "failed" },
        { username: "User15", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User16", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User17", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "completed" },
        { username: "User18", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "failed" },
        { username: "User19", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User20", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User21", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "completed" },
        { username: "User22", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "failed" },
        { username: "User23", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User24", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User25", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "completed" },
        { username: "User26", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "failed" },
        { username: "User27", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User28", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User29", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "completed" },
        { username: "User30", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "failed" },
        { username: "User31", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User32", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User33", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "completed" },
        { username: "User34", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "failed" },
        { username: "User35", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User36", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User37", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "completed" },
        { username: "User38", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "failed" },
        { username: "User39", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
        { username: "User40", profilePictue: "https://sortlist-core-api.s3.eu-west-1.amazonaws.com/691sw8s8dxjynerceh0xp1ge7duw", status: "in progress" },
    ];
    return { list }
}